github: []
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
  # Primary Support Options:
  - 'https://payments.cashfree.com/forms?code=trinity-mods-donation'  # UPI/INR (Cashfree Payment Form)
  - 'https://pay.cryptomus.com/wallet/823249d5-894b-403b-bd01-ef2394f2c472' # USDT (BSC) via Cryptomus
